// ============================================================
// CONTAO SCAFFOLD — CSS, Content-SQL, Defaults
// ============================================================

import { getThemeDefaults, getFontConfig, getGoogleFontsUrl } from '../theme-defaults.js'
import { sqlEsc } from '../redaxo-scaffold/utils.js'

// ============================================================
// CSS GENERATOR — Base CSS + per-Section CSS
// ============================================================

export function generateThemeCSS(themeConfig = {}, sectionsCss = '') {
  const mode = themeConfig.mode || 'light'
  const defaults = getThemeDefaults(mode)
  const primary = themeConfig.primary || '#2563eb'
  const secondary = themeConfig.secondary || '#7c3aed'
  const fontConfig = getFontConfig(themeConfig.font)

  const baseCss = `/* Generated by Deploy Dashboard — Contao Theme */
:root {
  --color-primary: ${primary};
  --color-secondary: ${secondary};
  --color-bg: ${defaults.bg};
  --color-surface: ${defaults.surface};
  --color-surface-alt: ${defaults.surfaceAlt};
  --color-text: ${defaults.text};
  --color-text-muted: ${defaults.textMuted};
  --color-text-inverted: ${defaults.textInverted};
  --color-border: ${defaults.border};
  --font-body: ${fontConfig.body};
  --font-heading: ${fontConfig.heading};
  --radius: 12px;
  --shadow: 0 4px 20px rgba(0,0,0,0.08);
  --transition: 0.3s ease;
}

/* Reset + Base */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; }
body {
  font-family: var(--font-body);
  background: var(--color-bg);
  color: var(--color-text);
  line-height: 1.6;
}
h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
  letter-spacing: -0.02em;
}
a { color: var(--color-primary); text-decoration: none; }
img { max-width: 100%; height: auto; }

/* Contao Layout-Reset — Contao's layout.min.css setzt floats, overflow:hidden etc. */
#wrapper, #container, #main, #main .inside { float: none; width: 100%; overflow: visible; }
.mod_article.block { overflow: visible; }

/* Container */
.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 1.5rem;
}

/* Navbar */
.navbar {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 1000;
  padding: 1rem 0;
  transition: all var(--transition);
  background: transparent;
}
.navbar--scrolled {
  background: ${mode === 'dark' ? 'rgba(10,10,10,0.95)' : 'rgba(255,255,255,0.95)'};
  backdrop-filter: blur(10px);
  box-shadow: 0 2px 20px rgba(0,0,0,0.1);
  padding: 0.5rem 0;
}
.navbar__inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.navbar__brand {
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--color-text-inverted);
}
.navbar__menu {
  display: flex;
  list-style: none;
  gap: 2rem;
}
.navbar__menu a {
  color: rgba(255,255,255,0.85);
  font-weight: 500;
  transition: color var(--transition);
}
.navbar__menu a:hover { color: #fff; }
.navbar--scrolled .navbar__brand { color: var(--color-text); }
.navbar--scrolled .navbar__menu a { color: var(--color-text-muted); }
.navbar--scrolled .navbar__menu a:hover { color: var(--color-primary); }
.navbar__toggle {
  display: none;
  flex-direction: column;
  gap: 5px;
  background: none;
  border: none;
  cursor: pointer;
}
.navbar__toggle span {
  width: 24px;
  height: 2px;
  background: var(--color-text-inverted);
  transition: var(--transition);
}
.navbar--scrolled .navbar__toggle span { background: var(--color-text); }
@media (max-width: 768px) {
  .navbar__toggle { display: flex; }
  .navbar__menu {
    display: none;
    position: absolute;
    top: 100%;
    left: 0;
    right: 0;
    flex-direction: column;
    padding: 1rem 1.5rem;
    gap: 0.5rem;
    background: ${mode === 'dark' ? 'rgba(10,10,10,0.98)' : 'rgba(255,255,255,0.98)'};
    backdrop-filter: blur(10px);
  }
  .navbar__menu--open { display: flex; }
}

/* Buttons */
.btn {
  display: inline-block;
  padding: 0.75rem 2rem;
  border-radius: var(--radius);
  font-weight: 600;
  cursor: pointer;
  transition: all var(--transition);
  border: none;
  font-size: 1rem;
}
.btn--primary {
  background: var(--color-primary);
  color: var(--color-text-inverted);
}
.btn--primary:hover {
  opacity: 0.9;
  transform: translateY(-2px);
  box-shadow: 0 8px 25px rgba(0,0,0,0.15);
}
.btn--secondary {
  background: transparent;
  color: var(--color-primary);
  border: 2px solid var(--color-primary);
}
.btn--secondary:hover {
  background: var(--color-primary);
  color: var(--color-text-inverted);
  transform: translateY(-2px);
}
.section--hero .btn--secondary,
.section--beitreten .btn--secondary,
[style*="gradient"] .btn--secondary {
  color: var(--color-text-inverted);
  border-color: rgba(255,255,255,0.5);
}
.section--hero .btn--secondary:hover,
.section--beitreten .btn--secondary:hover {
  background: rgba(255,255,255,0.15);
  border-color: #fff;
}
.btn--lg, .btn--large { padding: 1rem 2.5rem; font-size: 1.1rem; }

/* Sections */
.section {
  padding: clamp(4rem, 8vw, 7rem) 0;
}
.section__title {
  font-size: clamp(1.75rem, 3vw, 2.75rem);
  font-weight: 700;
  font-family: var(--font-heading);
  margin-bottom: 3rem;
  text-align: center;
  letter-spacing: -0.02em;
}

/* Footer */
.footer {
  background: ${mode === 'dark' ? '#050505' : '#111827'};
  color: ${mode === 'dark' ? '#9ca3af' : '#d1d5db'};
  padding: 2rem 0;
  text-align: center;
}
.footer a { color: var(--color-primary); }

/* Scroll Animation */
@keyframes fadeInUp {
  from { opacity: 0; transform: translateY(30px); }
  to { opacity: 1; transform: translateY(0); }
}
.section { animation: fadeInUp 0.6s ease both; }
`

  return baseCss + (sectionsCss ? '\n' + sectionsCss : '')
}

// ============================================================
// NAVBAR + FOOTER HTML — wird als erstes/letztes Content-Element eingefuegt
// ============================================================

export function generateNavbarHtml(projectName) {
  return `<nav class="navbar" id="navbar">
  <div class="container navbar__inner">
    <a href="/" class="navbar__brand">${projectName}</a>
    <button class="navbar__toggle" aria-label="Menu">
      <span></span><span></span><span></span>
    </button>
    <ul class="navbar__menu">
      <li><a href="#hero">Start</a></li>
      <li><a href="#about">Ueber uns</a></li>
      <li><a href="#services">Leistungen</a></li>
      <li><a href="#kontakt">Kontakt</a></li>
    </ul>
  </div>
</nav>`
}

export function generateFooterHtml(projectName) {
  return `<footer class="footer">
  <div class="container">
    <p>&copy; ${new Date().getFullYear()} ${projectName}. Alle Rechte vorbehalten.</p>
  </div>
</footer>`
}

// JavaScript fuer Smooth Scroll, Navbar Scroll-Effekt, Mobile Menu
// Wird als separate Datei geschrieben (Contao-Sanitizer blockt <script> in Content-Elementen)
export function generateMainJs() {
  return `// Smooth scroll
document.querySelectorAll('a[href^="#"]').forEach(function(a) {
  a.addEventListener('click', function(e) {
    e.preventDefault();
    var el = document.querySelector(a.getAttribute('href'));
    if (el) el.scrollIntoView({ behavior: 'smooth' });
  });
});
// Navbar scroll effect
window.addEventListener('scroll', function() {
  var navbar = document.getElementById('navbar');
  if (navbar) navbar.classList.toggle('navbar--scrolled', window.scrollY > 50);
});
// Mobile menu toggle
var toggle = document.querySelector('.navbar__toggle');
if (toggle) {
  toggle.addEventListener('click', function() {
    document.querySelector('.navbar__menu').classList.toggle('navbar__menu--open');
  });
}
`
}

// ============================================================
// SQL GENERATOR — Theme, Layout, Content
// ============================================================

export function generateContentSQL(sections, projectName, googleFontsUrl = null, adminEmail = 'info@robinherbeck.com') {
  const statements = ['SET NAMES utf8mb4;']

  // CSS-Link als head-Tag fuer das Layout (Google Fonts + theme.css)
  let headTags = ''
  if (googleFontsUrl) {
    headTags += `<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="${googleFontsUrl}">`
  }

  // Theme erstellen
  statements.push(
    `DELETE FROM tl_theme WHERE id = 1;`,
    `INSERT INTO tl_theme (id, name, author, tstamp) VALUES (1, ${sqlEsc('Starter Theme')}, ${sqlEsc('Deploy Dashboard')}, UNIX_TIMESTAMP());`,
  )

  // Layout erstellen — external CSS + JS ueber head-Tag einbinden
  const cssHeadTag = `<link rel="stylesheet" href="files/theme/style.css">`
  const jsHeadTag = `<script defer src="files/theme/main.js"></script>`
  const allHeadTags = headTags + cssHeadTag + jsHeadTag

  // modules: Serialisiertes PHP-Array — Artikel-Modul (mod=0) in Hauptspalte (col=main)
  // Ohne dieses Feld wirft Contao einen foreach-Fehler in PageRegular.php
  const modules = 'a:1:{i:0;a:3:{s:3:\\"mod\\";s:1:\\"0\\";s:3:\\"col\\";s:4:\\"main\\";s:6:\\"enable\\";s:1:\\"1\\";}}'
  const emptyArray = 'a:0:{}'

  statements.push(
    `DELETE FROM tl_layout WHERE id = 1;`,
    `INSERT INTO tl_layout (id, pid, name, template, head, modules, sections, external, externalJs, tstamp) VALUES (1, 1, ${sqlEsc('Standard')}, 'fe_page', ${sqlEsc(allHeadTags)}, '${modules}', '${emptyArray}', '${emptyArray}', '${emptyArray}', UNIX_TIMESTAMP());`,
  )

  // Seitenstruktur erstellen (contao:migrate legt nur Tabellen an, keine Seiten)
  // Root-Seite
  statements.push(
    `DELETE FROM tl_page WHERE id IN (1, 2);`,
    `INSERT INTO tl_page (id, pid, sorting, tstamp, title, alias, type, language, fallback, includeLayout, layout, published, adminEmail) VALUES (1, 0, 128, UNIX_TIMESTAMP(), ${sqlEsc(projectName)}, 'root', 'root', 'de', 1, 1, 1, 1, ${sqlEsc(adminEmail)});`,
  )

  // Startseite (regulaere Seite unter Root)
  statements.push(
    `INSERT INTO tl_page (id, pid, sorting, tstamp, title, alias, type, published) VALUES (2, 1, 128, UNIX_TIMESTAMP(), 'Startseite', 'startseite', 'regular', 1);`,
  )

  // Artikel fuer Startseite
  statements.push(
    `DELETE FROM tl_article WHERE pid = 2;`,
    `INSERT INTO tl_article (id, pid, sorting, tstamp, title, alias, inColumn, published) VALUES (1, 2, 128, UNIX_TIMESTAMP(), 'Startseite', 'startseite', 'main', 1);`,
  )

  // Bestehende Content-Elemente loeschen
  statements.push(
    `DELETE FROM tl_content WHERE pid = 1 AND ptable = 'tl_article';`,
  )

  // Navbar als erstes HTML-Element
  const navbarHtml = generateNavbarHtml(projectName)
  statements.push(
    `INSERT INTO tl_content (pid, ptable, type, html, sorting, tstamp) VALUES (1, 'tl_article', 'html', ${sqlEsc(navbarHtml)}, 64, UNIX_TIMESTAMP());`,
  )

  // Content-Elemente pro Section
  let sorting = 128
  for (const section of sections) {
    const html = `<section class="section section--${section.id}" id="${section.id}">\n${section.output}\n</section>`
    statements.push(
      `INSERT INTO tl_content (pid, ptable, type, html, sorting, tstamp) VALUES (1, 'tl_article', 'html', ${sqlEsc(html)}, ${sorting}, UNIX_TIMESTAMP());`,
    )
    sorting += 128
  }

  // Footer als letztes HTML-Element
  const footerHtml = generateFooterHtml(projectName)
  statements.push(
    `INSERT INTO tl_content (pid, ptable, type, html, sorting, tstamp) VALUES (1, 'tl_article', 'html', ${sqlEsc(footerHtml)}, ${sorting}, UNIX_TIMESTAMP());`,
  )

  return statements.join('\n')
}

// ============================================================
// DEFAULT CONTENT — Fallback wenn kein AI-Beschreibung
// ============================================================

export const DEFAULT_CONTAO_CONTENT = {
  theme: { primary: '#1e40af', secondary: '#7c3aed', mode: 'light', font: 'system' },
  meta: { title: 'Webseite', description: '' },
  sections: [
    {
      id: 'hero',
      name: 'Hero Section',
      data: { title: 'Willkommen', subtitle: 'Ihre professionelle Webpraesenz', ctaText: 'Mehr erfahren' },
      output: `<div class="container hero__content">
  <h1 class="hero__title">Willkommen</h1>
  <p class="hero__subtitle">Ihre professionelle Webpraesenz — modern, schnell und zuverlaessig</p>
  <a href="#kontakt" class="btn btn--primary btn--lg">Mehr erfahren</a>
</div>`,
      css: `.section--hero { min-height: 85vh; display: flex; align-items: center; background: linear-gradient(135deg, var(--color-primary), var(--color-secondary)); color: var(--color-text-inverted); }
.hero__content { text-align: center; }
.hero__title { font-size: clamp(2.5rem, 5vw, 4rem); font-weight: 800; margin-bottom: 1rem; }
.hero__subtitle { font-size: clamp(1.1rem, 2vw, 1.4rem); opacity: 0.9; margin-bottom: 2rem; max-width: 600px; margin-left: auto; margin-right: auto; }`,
    },
    {
      id: 'features',
      name: 'Leistungen',
      data: {},
      output: `<div class="container">
  <h2 class="section__title">Unsere Leistungen</h2>
  <div class="features__grid">
    <div class="features__card">
      <div class="features__icon">\u26a1</div>
      <h3>Schnell</h3>
      <p>Blitzschnelle Ladezeiten dank optimierter Technik</p>
    </div>
    <div class="features__card">
      <div class="features__icon">\ud83c\udfa8</div>
      <h3>Modern</h3>
      <p>Zeitgemaesses Design nach aktuellen Standards</p>
    </div>
    <div class="features__card">
      <div class="features__icon">\ud83d\udcf1</div>
      <h3>Responsiv</h3>
      <p>Optimiert fuer alle Geraete und Bildschirmgroessen</p>
    </div>
  </div>
</div>`,
      css: `.features__grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 2rem; }
.features__card { background: var(--color-surface); border-radius: var(--radius); padding: 2rem; text-align: center; transition: transform var(--transition), box-shadow var(--transition); }
.features__card:hover { transform: translateY(-4px); box-shadow: var(--shadow); }
.features__icon { font-size: 2.5rem; margin-bottom: 1rem; }
.features__card h3 { margin-bottom: 0.5rem; }
.features__card p { color: var(--color-text-muted); }`,
    },
    {
      id: 'about',
      name: 'Ueber uns',
      data: {},
      output: `<div class="container about__inner">
  <div class="about__text">
    <h2 class="section__title" style="text-align: left;">Ueber uns</h2>
    <p>Wir sind ein erfahrenes Team mit Leidenschaft fuer Qualitaet und Innovation. Seit ueber 10 Jahren realisieren wir erfolgreiche Webprojekte.</p>
    <ul class="about__highlights">
      <li>10+ Jahre Erfahrung</li>
      <li>100+ zufriedene Kunden</li>
      <li>Persoenliche Betreuung</li>
    </ul>
  </div>
</div>`,
      css: `.about__inner { max-width: 700px; }
.about__text p { color: var(--color-text-muted); font-size: 1.1rem; line-height: 1.8; margin-bottom: 1.5rem; }
.about__highlights { list-style: none; display: flex; flex-wrap: wrap; gap: 1rem; }
.about__highlights li { background: var(--color-surface); padding: 0.5rem 1.25rem; border-radius: var(--radius); font-weight: 500; }`,
    },
    {
      id: 'stats',
      name: 'Zahlen & Fakten',
      data: {},
      output: `<div class="container">
  <div class="stats__grid">
    <div class="stats__item"><span class="stats__value">500+</span><span class="stats__label">Projekte</span></div>
    <div class="stats__item"><span class="stats__value">10+</span><span class="stats__label">Jahre</span></div>
    <div class="stats__item"><span class="stats__value">99%</span><span class="stats__label">Zufriedenheit</span></div>
    <div class="stats__item"><span class="stats__value">24/7</span><span class="stats__label">Support</span></div>
  </div>
</div>`,
      css: `.section--stats { background: var(--color-surface-alt); }
.stats__grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 2rem; text-align: center; }
.stats__value { display: block; font-size: clamp(2rem, 4vw, 3rem); font-weight: 800; color: var(--color-primary); font-family: var(--font-heading); }
.stats__label { color: var(--color-text-muted); font-size: 0.95rem; }`,
    },
    {
      id: 'contact',
      name: 'Kontakt',
      data: {},
      output: `<div class="container contact__inner">
  <h2 class="section__title">Kontakt</h2>
  <div class="contact__grid">
    <div class="contact__card">
      <span class="contact__icon">\ud83d\udcde</span>
      <h3>Telefon</h3>
      <p>+49 123 456789</p>
    </div>
    <div class="contact__card">
      <span class="contact__icon">\u2709\ufe0f</span>
      <h3>E-Mail</h3>
      <p>info@example.com</p>
    </div>
    <div class="contact__card">
      <span class="contact__icon">\ud83d\udccd</span>
      <h3>Adresse</h3>
      <p>Musterstr. 1, 12345 Berlin</p>
    </div>
  </div>
</div>`,
      css: `.contact__grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 2rem; }
.contact__card { background: var(--color-surface); border-radius: var(--radius); padding: 2rem; text-align: center; }
.contact__icon { font-size: 2rem; display: block; margin-bottom: 0.75rem; }
.contact__card h3 { margin-bottom: 0.5rem; }
.contact__card p { color: var(--color-text-muted); }`,
    },
  ],
}
